### ISSUE TITLE
[Feature Request] RAND Operator

### ISSUE THREAD

**Issue by ForeverZer0** [Yamakaja/commanditems#23]
I wish to request a feature that I believe many users could find useful: the addition of a `RAND` function as possible operator that can be used within the `op` parameter when using `CALC`.

The `a` and `b` parameters would function as a minimum and maximum threshold, and the value could then of course be stored in the `target` parameter for further processing.

**Example Usage:**

```yaml
# Select a random  value between 100 and 500
{ action: CALC, a: "100", b: "500", op: RAND, target: "n", actions: [
  # Further processing or actions using this value
  { action: COMMAND, by: CONSOLE, command: "eco give {player} {n}" }
]} 
```

**Comment by Yamakaja** [comment]
Hey, i agree that a `RAND` op could be useful, but it is going to need some extra parameters:

* Which datatype do we need: floats or integers (Whole numbers)
* Which distribution should we pick those numbers from, and
which distributions are interesting / should be supported (Uniform, Exponential, Gaussian, Rayleigh, etc.). How should parameters to these distributions be passed along?
* Should there be support for generating multiple values, so a 3D offset doesn't need three nested `RAND` ops?

I'll see what i can do this week

**Comment by ForeverZer0** [comment]
Sounds great! I was giving a low-complexity example, but the more nuanced features you stated would make it even more powerful and useful, allowing for even more possibilities. I look forward to seeing what you can achieve with this plugin, it has already become a standard addition to any server I run, great work.

**Comment by Yamakaja** [comment]
@ForeverZer0 Is the new `MATH_EXPR` something you can work with? https://github.com/Yamakaja/commanditems#math_expr

**Comment by ForeverZer0** [comment]
Looks great, well above and beyond what I could have hoped for. Thank you very much for considering this request and implementing it so quickly.
