### ISSUE TITLE
A way to remove ItemFlags

### ISSUE THREAD

**Issue by tika** [Yamakaja/commanditems#24]
If there isn't already a way to remove ItemFlags from an item, it would be a nice addition as it creates a mess as shown underneath

![image](https://user-images.githubusercontent.com/48658947/129235128-7aa48baf-239c-4a1f-b5b8-985c60404dbe.png)

**Comment by Yamakaja** [comment]
Are you referring to the debug information that you enabled by pressing F3+h?

**Comment by tika** [comment]
ItemFlags: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/ItemFlag.html
