### ISSUE TITLE
Hex/RGB color codes

### ISSUE THREAD

**Issue by tika** [Yamakaja/commanditems#25]
Support for hex colors?

**Comment by Yamakaja** [comment]
Uh, in what context? (I.e. where do you want to use RGB colors, and where is that even possible? Banners maybe?)

**Comment by tika** [comment]
In names of items, descriptions of items

**Comment by Yamakaja** [comment]
Are you referring to the normal `§[0-9a-f]` / `&[0-9a-f]` codes or is there now a way to specify arbitrary colors?

**Comment by tika** [comment]
Ah, in 1.17 they added support for RGB color codes, I can create a PR for this feature?

**Comment by Yamakaja** [comment]
Ohh, i see. Sure, why not :)

**Comment by tika** [comment]
This requires the 1.17 API however as it's specifically for that version

**Comment by Yamakaja** [comment]
Mhm, this needs to be implemented in a backwards compatible manner. I'll take a look at the API, maybe there is a good way to do that.
