### ISSUE TITLE
add function to disable item if they have a perm

### ISSUE THREAD

**Issue by CaszGamerMD** [Yamakaja/commanditems#5]
items that grant permissions, should have an easy function to prevent repeat use.

**Comment by CaszGamerMD** [comment]
never used gardle, and its not letting me build,

please add:
        if (!itemDefinition.getAlreadyUsed().equals("") && event.getPlayer().hasPermission(itemDefinition.getAlreadyUsed())){
            event.getPlayer().sendMessage(ChatColor.RED + "You have used this item!");
            return;
        }
after line 118 "if (!event.getPlayer().hasPermission("cmdi.item." + command))"
of CommandItemManager.java

also add:
 @JsonProperty
    private String alreadyUsed;

public String getAlreadyUsed() {
        return alreadyUsed;
    }

to ItemDefinition please <3

**Comment by Yamakaja** [comment]
Modern permissions plugins allow you to give players and groups "negated permissions", i.e. take away permissions that they would usually inherit.
